In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer # it is for handling missing value
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df.drop(columns = ['has_covid']), df['has_covid'], test_size = 0.2)

In [8]:
X_train.shape, X_test.shape

((80, 5), (20, 5))

In [9]:
X_train

age  gender  fever   cough       city
15   70    Male  103.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
43   22  Female   99.0    Mild  Bangalore
32   34  Female  101.0  Strong      Delhi
..  ...     ...    ...     ...        ...
18   64  Female   98.0    Mild  Bangalore
72   83  Female  101.0    Mild    Kolkata
20   12    Male   98.0  Strong  Bangalore
6    14    Male  101.0  Strong  Bangalore
80   14  Female   99.0    Mild     Mumbai

[80 rows x 5 columns]

# Normal Way of encoding

In [13]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_train[['fever']])

X_train_fever

array([[103.        ],
       [100.        ],
       [100.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [100.91780822],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [103.        ],
       [100.91780822],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [104.        ],
       [103.        ],
       [100.        ],
       [100.91780822],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [100.91780822],
       [104.        ],
       [ 98.        ],
       [100.91780822],
       [103.        ],
       [103.        ],
       [100.91780822],
       [ 99.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [ 98

In [14]:
# Ordinal encoding -> cough
oe = OrdinalEncoder(categories = [['Mild', 'Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_train[['cough']])

X_train_cough

array([[1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],

In [15]:
X_train_cough.shape

(80, 1)

In [18]:
# One Hot Encoding -> gender, city
ohe = OneHotEncoder(drop = 'first', sparse = False)
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# also for test data
X_test_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

X_train_gender_city.shape

C:\python3.7\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\python3.7\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 4)

In [19]:
X_train_gender_city

array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],


In [21]:
# Extracting Age
X_train_age = X_train.drop(columns = ['gender', 'fever', 'cough', 'city']).values

# also for test data
X_test_age = X_train.drop(columns = ['gender', 'fever', 'cough', 'city']).values

X_train_age

array([[70],
       [55],
       [19],
       [22],
       [34],
       [80],
       [20],
       [34],
       [82],
       [19],
       [33],
       [81],
       [17],
       [11],
       [68],
       [75],
       [11],
       [73],
       [34],
       [64],
       [80],
       [40],
       [ 6],
       [50],
       [27],
       [82],
       [12],
       [31],
       [26],
       [65],
       [10],
       [44],
       [84],
       [25],
       [24],
       [38],
       [16],
       [69],
       [75],
       [65],
       [69],
       [34],
       [74],
       [73],
       [15],
       [25],
       [48],
       [ 5],
       [60],
       [38],
       [83],
       [10],
       [64],
       [18],
       [47],
       [46],
       [16],
       [42],
       [51],
       [51],
       [59],
       [42],
       [27],
       [54],
       [66],
       [ 5],
       [69],
       [ 8],
       [19],
       [20],
       [20],
       [23],
       [47],
       [24],
       [42],
       [64],
       [83],

In [22]:
X_train_age.shape

(80, 1)

In [23]:
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis = 1)
# also for test data
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis = 1)
X_train_transformed

array([[ 70.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 55.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 80.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 20.        , 100.91780822,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          1.    

In [24]:
X_train_transformed.shape

(80, 7)

# Columns Transformer way of encoding

In [25]:
from sklearn.compose import ColumnTransformer

In [31]:
X_train.head(1)

age gender  fever   cough     city
15   70   Male  103.0  Strong  Kolkata

In [32]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
    ('tnf3', OneHotEncoder(sparse = False, drop= 'first'), ['gender', 'city'])
], remainder = 'passthrough')

In [34]:
transformer.fit_transform(X_train).shape

C:\python3.7\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [35]:
transformer.transform(X_test).shape

(20, 7)